### ISSUE TITLE
Play clock, 90 seconds

### ISSUE THREAD

**Issue by Smitty4263** [h4wduk3n/NCAA06Next#218]
After calling a time out the play clock starts at 90 seconds. This usually leads the CPU to wait until it hits at least 40 seconds before snapping the ball.

**Comment by antdroidx** [comment]
We are aware of this, and looking to see if we can reduce this time.

**Comment by antdroidx** [comment]
This is resolved in v12.2. We released a preview patch on the server. We will release a public v12.2 version this month.
