### ISSUE TITLE
Notre Dame

### ISSUE THREAD

**Issue by GrimTheGamingReaper** [h4wduk3n/NCAA06Next#25]
Notre Dame numbers appear to be black. For home and away. when in game .

**Comment by antdroidx** [comment]
![image](https://user-images.githubusercontent.com/24241868/169955304-1b8ec735-29b4-4afa-8399-1973fd221aff.png)

![image](https://user-images.githubusercontent.com/24241868/169955322-3d4bdfd2-31ac-46bd-9efc-f629fc7c22c5.png)

**Comment by antdroidx** [comment]
Resolved in next release
