### ISSUE TITLE
tennessee uniform bugs

### ISSUE THREAD

**Issue by cookybots** [h4wduk3n/NCAA06Next#46]
the numbers are grey i think they should be white or orange?
![firefox_jCIVBpD4UR](https://user-images.githubusercontent.com/106839110/171935662-fef21a0e-f3d1-4798-8d7e-b0dea62b474b.png)

**Comment by antdroidx** [comment]
This may not be able to be fixed easily since the NCAA 06 game re-uses the same numbers as Home default uniforms for alt

**Comment by antdroidx** [comment]
Also discovered by @cookybots 

![image](https://user-images.githubusercontent.com/24241868/173439604-8ad3fe92-50f1-4b1b-8494-f47e02d006e7.png)


![image](https://user-images.githubusercontent.com/24241868/173439628-6060e2a3-77d1-49a6-b9d2-45e3d347e069.png)

**Comment by antdroidx** [comment]
![image](https://user-images.githubusercontent.com/24241868/173481912-e47db57e-9e7c-42ce-84c2-daa6606bfe1c.png)

resolved
