### ISSUE TITLE
Iowa home numbers issue

### ISSUE THREAD

**Issue by jet5195** [h4wduk3n/NCAA06Next#47]
![Screenshot_54.png](https://user-images.githubusercontent.com/7342657/171937862-9a06b270-2e26-41e2-8974-921ee3f979f5.png)

**Comment by antdroidx** [comment]
![Screenshot 2022-06-04 171241](https://user-images.githubusercontent.com/24241868/172029670-8c523672-9d81-485f-b74a-e0479c2c5f47.png)

Resolved in next update

**Comment by antdroidx** [comment]
broken again.

**Comment by antdroidx** [comment]
![image](https://user-images.githubusercontent.com/24241868/173441280-0c6fab8b-70bc-4e33-af68-df2a25e8f57c.png)

**Comment by antdroidx** [comment]
![image](https://user-images.githubusercontent.com/24241868/173475698-67af5264-6105-426b-91de-92720d16a6ed.png)

Resolved
