### ISSUE TITLE
Upscale some uniforms to 4X+

### ISSUE THREAD

**Issue by antdroidx** [h4wduk3n/NCAA06Next#56]
This will help reduce blurriness in higher resolution settings.

**Comment by antdroidx** [comment]
New templates at 4x (1024x1024) res distributed to team members and will be used moving forward.

Older uniforms will/may be updated in future, but loq priority.

**Comment by antdroidx** [comment]
This is being worked on by BUBeavers92, xflamesxofxhopex and 4Star.

**Comment by h4wduk3n** [comment]
@antdroidx for reference please link your uniform tracker spreadsheet here

**Comment by antdroidx** [comment]
Sheet doesnt track HD unis (yet)
https://docs.google.com/spreadsheets/d/1FXPgxhwS4Jtf4lWyz19sRBgOeCyRNiBe/edit?usp=sharing&ouid=103205099795747230187&rtpof=true&sd=true

**Comment by antdroidx** [comment]
CookyBots Helped Find these left:

BIG TEN:  
Indiana
Nebraska
Purdue
Rutgers
Wisconsin

ACC
NC State
Virginia
Louisville

Big XII
Iowa State

Independents
Army

SEC
Missouri

**Comment by antdroidx** [comment]
Nebraska Done. Oregon/Oregon State/Washington done.

CookyBots Helped Find these left:

BIG TEN:
Indiana -- Ok and!?
Purdue
Rutgers -- 4star?
Wisconsin -- Ok and!?

ACC
NC State -- 4star
Virginia
Louisville

Big XII
Iowa State

Independents
Army --BUBeavers92

SEC
Missouri

PAC
Wash State - Antdroid
TBD

**Comment by antdroidx** [comment]
WSU/Missouri completed.

BIG TEN:
Indiana -- Ok and!?
Purdue
Rutgers -- 4star?
Wisconsin -- Ok and!?

ACC
NC State -- 4star
Virginia
Louisville

Big XII
Iowa State

Independents
Army --BUBeavers92

PAC
TBD

**Comment by antdroidx** [comment]
Iowa State/Purdue done.

Indiana -- Ok and!?
Rutgers -- 4star?
Wisconsin -- Ok and!?
NC State -- 4star
Virginia
Louisville
Army --BUBeavers92

**Comment by h4wduk3n** [comment]
PAC Done

**Comment by jet5195** [comment]
Virginia done

**Comment by antdroidx** [comment]
Wisconsin - OK and !? / JD637 numbers
Rutgers - JD637
